### ISSUE TITLE
request: any plans to incorporate lists from elsewhere

### ISSUE THREAD

**Issue by nicoleahmed** [palant/malicious-extensions-list#3]
Hi Wladimir
Excellent work you have been doing - thank you

There have been other researchers and teams finding bad extensions as a result of your work.

I wondered if you have any plans to incorporate these lists into your list? e.g. https://blog.avast.com/malicious-extensions-chrome-web-store

Though many/most extensions will have been removed from the chrome store - adding to your list would help check where these extensions may remain installed

Thanks

**Comment by palant** [comment]
I didn’t realize that I didn’t answer this question. No, I don’t want to incorporate lists from elsewhere – I cannot do it without verifying first, and verifying would require considerable effort.

On the bright side: AFAIK all extensions in this Avast blog post have been disabled by Google. And this is much better than this repository which will reach only few users if any.
